[package]
name = "oper"
version = "0.2.0"
authors = ["Florian Bramer <elektronenhirn@gmail.com>"]
description = "Command line tool to browse changes across multiple git repositories managed by google's git-repo tool"
edition = "2018"
categories = ["command-line-interface", "gui", "git-repo"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/elektronenhirn/oper.git"

[dependencies]
chrono = "0.4.7"
clap = "2.33.0"
cursive = "0.12"
git2 = "0.9.1"
indicatif = "0.11.0"
log = "0.4.7"
simple_logger = "1.3.0"
time = "0.1.39"