name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ncurses
      run: sudo apt-get install libncurses6-dev 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
